# Workflow derived from https://github.com/FabrizioSandri/RcppDeepState-action/blob/main/.github/workflows/action-test.yaml
on:
  pull_request:
    branches:
      - '*'

name: "RcppDeepState + valgrind"

jobs:
  RcppDeepState:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: FabrizioSandri/RcppDeepState-action@main
        with:
          comment: 'true'
          max_inputs: 10
          seed: 5
          fail_ci_if_error: 'true'
  
